spring.application.name=API-Gateway
server.port=8080


services.auth.url=http://auth-service:8080
services.user.url=http://user-service:8080
services.order.url=http://order-service:8080
services.payment.url=http://payment-service:8080

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${services.auth.url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=registration-saga
spring.cloud.gateway.routes[1].uri=forward:/api/gateway/register
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/register

spring.cloud.gateway.routes[2].id=user-service-secured
spring.cloud.gateway.routes[2].uri=${services.user.url}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=${services.order.url}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/orders/**, /api/items/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=${services.payment.url}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=5s
jwt.secret=${JWT_SECRET}